services:
  app:
    container_name: capstone_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /data/upload:/data/upload
    depends_on:
     mysql-prod:
         condition: service_healthy
     elastic-prod:
         condition: service_healthy
    restart: on-failure
    profiles:
      - production

  nginx:
    container_name: capstone_nginx
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    profiles:
      - production

  mysql-prod:
    image: mysql:8.0
    container_name: capstone_MySQL
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: capstone_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - production

  mysql-dev:
    image: mysql:8.0
    container_name: capstone_MySQL_dev
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: capstone_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - /var/lib/mysql
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - development

  elastic-prod:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: capstone_elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - production

  elastic-dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: capstone_elasticsearch_dev
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - development

volumes:
  db_data:
  db_data_dev:
  es_data:
  es_data_dev: