services:
  app:
    container_name: capstone_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
     mysql:
         condition: service_healthy
     elasticsearch:
         condition: service_healthy
    restart: on-failure
    profiles:
      - production

  mysql:
    image: mysql:8.0
    container_name: capstone_MySQL
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: capstone_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - /var/lib/mysql
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - production
      - development

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: capstone_elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/lib/elasticsearch/data
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - production
      - development
