name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
  
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SSH
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p ${{ secrets.SERVER_PORT }} "rm -rf ~/app && mkdir -p ~/app"
        scp -P ${{ secrets.SERVER_PORT }} -r * ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/app
    
    - name: Create .env file on the server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p ${{ secrets.SERVER_PORT }} << EOF
          cat <<EOT >> ~/app/.env
          PORT=${{ secrets.PORT }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOT
    
          cat <<EOT >> ~/app/.env.production
          PORT=${{ secrets.PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          ES_HOST=${{ secrets.ES_HOST }}
          ES_PORT=${{ secrets.ES_PORT }}
          EOT
        EOF
        

    - name: Deploy with Docker Compose
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p ${{ secrets.SERVER_PORT }} "cd ~/app && docker compose --profile production down && docker compose --profile production up -d --build"
